# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
	# check these on https://fabricmc.net/versions.html

minecraft_version=26.1.2
loader_version=0.18.6
loom_version=1.16-SNAPSHOT

# Fabric API
fabric_api_version=0.145.3+26.1.1

# Mod Properties
mod_version = 2.0.67.676769-fork
maven_group = com.luneruniverse.minecraft.mod.nbteditor
archives_base_name = nbteditor
